/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidosIndexRouteImport } from './routes/pedidos.index'
import { Route as PedidosInternosIndexRouteImport } from './routes/pedidos-internos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PedidosOrderIdRouteImport } from './routes/pedidos.$orderId'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTrasladosRouteImport } from './routes/admin.traslados'
import { Route as AdminStockBodegasRouteImport } from './routes/admin.stock-bodegas'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReportesRouteImport } from './routes/admin.reportes'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as AdminPedidosInternosRouteImport } from './routes/admin.pedidos-internos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminLotesRouteImport } from './routes/admin.lotes'
import { Route as AdminKardexRouteImport } from './routes/admin.kardex'
import { Route as AdminInventarioRouteImport } from './routes/admin.inventario'
import { Route as AdminDependenciasRouteImport } from './routes/admin.dependencias'
import { Route as AdminCentrosCostoRouteImport } from './routes/admin.centros-costo'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminBodegasRouteImport } from './routes/admin.bodegas'

const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosInternosIndexRoute = PedidosInternosIndexRouteImport.update({
  id: '/pedidos-internos/',
  path: '/pedidos-internos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PedidosOrderIdRoute = PedidosOrderIdRouteImport.update({
  id: '/pedidos/$orderId',
  path: '/pedidos/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrasladosRoute = AdminTrasladosRouteImport.update({
  id: '/traslados',
  path: '/traslados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockBodegasRoute = AdminStockBodegasRouteImport.update({
  id: '/stock-bodegas',
  path: '/stock-bodegas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosInternosRoute = AdminPedidosInternosRouteImport.update({
  id: '/pedidos-internos',
  path: '/pedidos-internos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLotesRoute = AdminLotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKardexRoute = AdminKardexRouteImport.update({
  id: '/kardex',
  path: '/kardex',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventarioRoute = AdminInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDependenciasRoute = AdminDependenciasRouteImport.update({
  id: '/dependencias',
  path: '/dependencias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCentrosCostoRoute = AdminCentrosCostoRouteImport.update({
  id: '/centros-costo',
  path: '/centros-costo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBodegasRoute = AdminBodegasRouteImport.update({
  id: '/bodegas',
  path: '/bodegas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/productos': typeof ProductosRoute
  '/admin/bodegas': typeof AdminBodegasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/centros-costo': typeof AdminCentrosCostoRoute
  '/admin/dependencias': typeof AdminDependenciasRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/kardex': typeof AdminKardexRoute
  '/admin/lotes': typeof AdminLotesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/pedidos-internos': typeof AdminPedidosInternosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/stock-bodegas': typeof AdminStockBodegasRoute
  '/admin/traslados': typeof AdminTrasladosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/pedidos-internos/': typeof PedidosInternosIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/productos': typeof ProductosRoute
  '/admin/bodegas': typeof AdminBodegasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/centros-costo': typeof AdminCentrosCostoRoute
  '/admin/dependencias': typeof AdminDependenciasRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/kardex': typeof AdminKardexRoute
  '/admin/lotes': typeof AdminLotesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/pedidos-internos': typeof AdminPedidosInternosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/stock-bodegas': typeof AdminStockBodegasRoute
  '/admin/traslados': typeof AdminTrasladosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/pedidos-internos': typeof PedidosInternosIndexRoute
  '/pedidos': typeof PedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/productos': typeof ProductosRoute
  '/admin/bodegas': typeof AdminBodegasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/centros-costo': typeof AdminCentrosCostoRoute
  '/admin/dependencias': typeof AdminDependenciasRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/kardex': typeof AdminKardexRoute
  '/admin/lotes': typeof AdminLotesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/pedidos-internos': typeof AdminPedidosInternosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/stock-bodegas': typeof AdminStockBodegasRoute
  '/admin/traslados': typeof AdminTrasladosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/pedidos-internos/': typeof PedidosInternosIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/carrito'
    | '/productos'
    | '/admin/bodegas'
    | '/admin/categorias'
    | '/admin/centros-costo'
    | '/admin/dependencias'
    | '/admin/inventario'
    | '/admin/kardex'
    | '/admin/lotes'
    | '/admin/pedidos'
    | '/admin/pedidos-internos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/roles'
    | '/admin/stock-bodegas'
    | '/admin/traslados'
    | '/admin/usuarios'
    | '/pedidos/$orderId'
    | '/admin/'
    | '/pedidos-internos/'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrito'
    | '/productos'
    | '/admin/bodegas'
    | '/admin/categorias'
    | '/admin/centros-costo'
    | '/admin/dependencias'
    | '/admin/inventario'
    | '/admin/kardex'
    | '/admin/lotes'
    | '/admin/pedidos'
    | '/admin/pedidos-internos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/roles'
    | '/admin/stock-bodegas'
    | '/admin/traslados'
    | '/admin/usuarios'
    | '/pedidos/$orderId'
    | '/admin'
    | '/pedidos-internos'
    | '/pedidos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/carrito'
    | '/productos'
    | '/admin/bodegas'
    | '/admin/categorias'
    | '/admin/centros-costo'
    | '/admin/dependencias'
    | '/admin/inventario'
    | '/admin/kardex'
    | '/admin/lotes'
    | '/admin/pedidos'
    | '/admin/pedidos-internos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/roles'
    | '/admin/stock-bodegas'
    | '/admin/traslados'
    | '/admin/usuarios'
    | '/pedidos/$orderId'
    | '/admin/'
    | '/pedidos-internos/'
    | '/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarritoRoute: typeof CarritoRoute
  ProductosRoute: typeof ProductosRoute
  PedidosOrderIdRoute: typeof PedidosOrderIdRoute
  PedidosInternosIndexRoute: typeof PedidosInternosIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos-internos/': {
      id: '/pedidos-internos/'
      path: '/pedidos-internos'
      fullPath: '/pedidos-internos/'
      preLoaderRoute: typeof PedidosInternosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pedidos/$orderId': {
      id: '/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/pedidos/$orderId'
      preLoaderRoute: typeof PedidosOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/traslados': {
      id: '/admin/traslados'
      path: '/traslados'
      fullPath: '/admin/traslados'
      preLoaderRoute: typeof AdminTrasladosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock-bodegas': {
      id: '/admin/stock-bodegas'
      path: '/stock-bodegas'
      fullPath: '/admin/stock-bodegas'
      preLoaderRoute: typeof AdminStockBodegasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos-internos': {
      id: '/admin/pedidos-internos'
      path: '/pedidos-internos'
      fullPath: '/admin/pedidos-internos'
      preLoaderRoute: typeof AdminPedidosInternosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lotes': {
      id: '/admin/lotes'
      path: '/lotes'
      fullPath: '/admin/lotes'
      preLoaderRoute: typeof AdminLotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kardex': {
      id: '/admin/kardex'
      path: '/kardex'
      fullPath: '/admin/kardex'
      preLoaderRoute: typeof AdminKardexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventario': {
      id: '/admin/inventario'
      path: '/inventario'
      fullPath: '/admin/inventario'
      preLoaderRoute: typeof AdminInventarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dependencias': {
      id: '/admin/dependencias'
      path: '/dependencias'
      fullPath: '/admin/dependencias'
      preLoaderRoute: typeof AdminDependenciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/centros-costo': {
      id: '/admin/centros-costo'
      path: '/centros-costo'
      fullPath: '/admin/centros-costo'
      preLoaderRoute: typeof AdminCentrosCostoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bodegas': {
      id: '/admin/bodegas'
      path: '/bodegas'
      fullPath: '/admin/bodegas'
      preLoaderRoute: typeof AdminBodegasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBodegasRoute: typeof AdminBodegasRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminCentrosCostoRoute: typeof AdminCentrosCostoRoute
  AdminDependenciasRoute: typeof AdminDependenciasRoute
  AdminInventarioRoute: typeof AdminInventarioRoute
  AdminKardexRoute: typeof AdminKardexRoute
  AdminLotesRoute: typeof AdminLotesRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminPedidosInternosRoute: typeof AdminPedidosInternosRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminStockBodegasRoute: typeof AdminStockBodegasRoute
  AdminTrasladosRoute: typeof AdminTrasladosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBodegasRoute: AdminBodegasRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminCentrosCostoRoute: AdminCentrosCostoRoute,
  AdminDependenciasRoute: AdminDependenciasRoute,
  AdminInventarioRoute: AdminInventarioRoute,
  AdminKardexRoute: AdminKardexRoute,
  AdminLotesRoute: AdminLotesRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminPedidosInternosRoute: AdminPedidosInternosRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminStockBodegasRoute: AdminStockBodegasRoute,
  AdminTrasladosRoute: AdminTrasladosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CarritoRoute: CarritoRoute,
  ProductosRoute: ProductosRoute,
  PedidosOrderIdRoute: PedidosOrderIdRoute,
  PedidosInternosIndexRoute: PedidosInternosIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
